# Fichier : docker-compose.yml

services:
  neo4j:
    build: 
      context: . 
    
    container_name: neo4j-graph-db
    hostname: neo4j
    ports:
      - "7474:7474" # Neo4j Browser (HTTP)
      - "7687:7687" # Bolt protocol (Driver)
    
    # Volumes pour la persistance des données et des logs.
    volumes:
      - ./data:/data         # Base de données persistante
      - ./logs:/logs         # Logs
      # NOTE: Le volume pour /import est retiré car le script init-db.cypher 
      # est copié via le Dockerfile pour s'assurer de son exécution initiale.
    
    environment:
      # --- Authentification (Celle-ci suffit pour le user/password et désactive le changement forcé) ---
      NEO4J_AUTH: neo4j/password
      
      # --- Licence (Obligatoire) ---
      NEO4J_ACCEPT_LICENSE_AGREEMENT: 'yes'
      
      # NOTE : Les variables qui causaient des erreurs de nommage ont été retirées
      # car les valeurs par défaut de Neo4j (base 'neo4j', pas de changement de mdp forcé) suffisent.
