services:
  neo4j:
    build: ./neo4j
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/test1234
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_PLUGINS=["apoc"]
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    depends_on:
      - neo4j

  api:
    build: ./api
    container_name: api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEO4J_HOST=neo4j
      - NEO4J_USER=neo4j
      - NEO4J_PASS=test1234
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - neo4j
    restart: unless-stopped