services:
  neo4j:
    build: ./neo4j
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/test1234
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_PLUGINS=["apoc"]
    volumes:
      - neo4j_data:/data
      - ./neo4j/init:/docker-entrypoint-initdb.d
    restart: unless-stopped

  frontend:
    build: ./filmfinder
    container_name: frontend
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    depends_on:
      - neo4j

volumes:
  neo4j_data:
