services:
  neo4j:
    build: ./neo4j
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/test1234
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_PLUGINS=["apoc"]
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "test1234", "RETURN 1"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 40s

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    depends_on:
      neo4j:
        condition: service_healthy

  api:
    build: ./api
    container_name: api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEO4J_HOST=neo4j
      - NEO4J_USER=neo4j
      - NEO4J_PASS=test1234
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      neo4j:
        condition: service_healthy
    restart: unless-stopped

volumes:
  neo4j_data:
  neo4j_logs: